spring.application.name=dev-platform
server.address=127.0.0.1
platform.git.host=${GIT_SERVER_HOST:}
platform.git.port=${GIT_SERVER_PORT:22}
platform.git.username=${GIT_SERVER_USER:}
platform.git.password=${GIT_SERVER_PASSWORD:}
platform.git.base-path=${GIT_SERVER_BASE_PATH:}
platform.git.known-hosts=${GIT_SERVER_KNOWN_HOSTS:}
platform.git.timeout-seconds=15
platform.git.sudo-enabled=${GIT_SERVER_SUDO_ENABLED:false}
platform.git.sudo-username=${GIT_SERVER_SUDO_USER:git}
platform.git.sudo-password=${GIT_SERVER_SUDO_PASSWORD:}
platform.git.clone-username=${GIT_SERVER_CLONE_USER:}
